[package]
name = "pong_rust-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
rand = "0.9.0"

[build]
build-stage = 1
target = [ "x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu" ]
